---
name: CI-CD GKE Deployment

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore: .github/**
  pull_request:
    branches:
      - master
    paths-ignore: .github/**  
env:
  PROJECT_ID: absolute-cache-468112-e2
  REGION: asia-south1
  ZONE: asia-south1-a
  CLUSTER_NAME: my-gke-cluster
  IMAGE_NAME: gcr.io/absolute-cache-468112-e2/python-app
  
jobs:
  infra-deploy:
    name: Terraform Apply GKE
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.5

    - name: Terraform Init
      run: terraform init
      working-directory: ./gcp-infra
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_TERRAFORM_GKE }}
      

    - name: Terraform plan
      run: terraform plan
      working-directory: ./gcp-infra
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_TERRAFORM_GKE }}


    - name: Terraform Apply
      run: terraform apply -auto-approve
      env:
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_TERRAFORM_GKE }}
      working-directory: ./gcp-infra  


  #gke-deploy:
  
